--Countries
insert into plenum.country (name) values ('Andorra');
insert into plenum.country (name) values ('United Arab Emirates');
insert into plenum.country (name) values ('Afghanistan');
insert into plenum.country (name) values ('Antigua and Barbuda');
insert into plenum.country (name) values ('Anguilla');
insert into plenum.country (name) values ('Albania');
insert into plenum.country (name) values ('Armenia');
insert into plenum.country (name) values ('Angola');
insert into plenum.country (name) values ('Antarctica');
insert into plenum.country (name) values ('Argentina');
insert into plenum.country (name) values ('American Samoa');
insert into plenum.country (name) values ('Austria');
insert into plenum.country (name) values ('Australia');
insert into plenum.country (name) values ('Aruba');
insert into plenum.country (name) values ('Åland Islands');
insert into plenum.country (name) values ('Azerbaijan');
insert into plenum.country (name) values ('Bosnia and Herzegovina');
insert into plenum.country (name) values ('Barbados');
insert into plenum.country (name) values ('Bangladesh');
insert into plenum.country (name) values ('Belgium');
insert into plenum.country (name) values ('Burkina Faso');
insert into plenum.country (name) values ('Bulgaria');
insert into plenum.country (name) values ('Bahrain');
insert into plenum.country (name) values ('Burundi');
insert into plenum.country (name) values ('Benin');
insert into plenum.country (name) values ('Saint Barthélemy');
insert into plenum.country (name) values ('Bermuda');
insert into plenum.country (name) values ('Brunei Darussalam');
insert into plenum.country (name) values ('Bolivia');
insert into plenum.country (name) values ('Caribbean Netherlands ');
insert into plenum.country (name) values ('Brazil');
insert into plenum.country (name) values ('Bahamas');
insert into plenum.country (name) values ('Bhutan');
insert into plenum.country (name) values ('Bouvet Island');
insert into plenum.country (name) values ('Botswana');
insert into plenum.country (name) values ('Belarus');
insert into plenum.country (name) values ('Belize');
insert into plenum.country (name) values ('Canada');
insert into plenum.country (name) values ('Cocos (Keeling) Islands');
insert into plenum.country (name) values ('Democratic Republic of Congo');
insert into plenum.country (name) values ('Central African Republic');
insert into plenum.country (name) values ('Congo');
insert into plenum.country (name) values ('Switzerland');
insert into plenum.country (name) values ('Côte d''Ivoire');
insert into plenum.country (name) values ('Cook Islands');
insert into plenum.country (name) values ('Chile');
insert into plenum.country (name) values ('Cameroon');
insert into plenum.country (name) values ('China');
insert into plenum.country (name) values ('Colombia');
insert into plenum.country (name) values ('Costa Rica');
insert into plenum.country (name) values ('Cuba');
insert into plenum.country (name) values ('Cape Verde');
insert into plenum.country (name) values ('Curaçao');
insert into plenum.country (name) values ('Christmas Island');
insert into plenum.country (name) values ('Cyprus');
insert into plenum.country (name) values ('Czech Republic');
insert into plenum.country (name) values ('Germany');
insert into plenum.country (name) values ('Djibouti');
insert into plenum.country (name) values ('Denmark');
insert into plenum.country (name) values ('Dominica');
insert into plenum.country (name) values ('Dominican Republic');
insert into plenum.country (name) values ('Algeria');
insert into plenum.country (name) values ('Ecuador');
insert into plenum.country (name) values ('Estonia');
insert into plenum.country (name) values ('Egypt');
insert into plenum.country (name) values ('Western Sahara');
insert into plenum.country (name) values ('Eritrea');
insert into plenum.country (name) values ('Spain');
insert into plenum.country (name) values ('Ethiopia');
insert into plenum.country (name) values ('Finland');
insert into plenum.country (name) values ('Fiji');
insert into plenum.country (name) values ('Falkland Islands');
insert into plenum.country (name) values (' Federated States of Micronesia');
insert into plenum.country (name) values ('Faroe Islands');
insert into plenum.country (name) values ('France');
insert into plenum.country (name) values ('Gabon');
insert into plenum.country (name) values ('United Kingdom');
insert into plenum.country (name) values ('Grenada');
insert into plenum.country (name) values ('Georgia');
insert into plenum.country (name) values ('French Guiana');
insert into plenum.country (name) values ('Guernsey');
insert into plenum.country (name) values ('Ghana');
insert into plenum.country (name) values ('Gibraltar');
insert into plenum.country (name) values ('Greenland');
insert into plenum.country (name) values ('Gambia');
insert into plenum.country (name) values ('Guinea');
insert into plenum.country (name) values ('Guadeloupe');
insert into plenum.country (name) values ('Equatorial Guinea');
insert into plenum.country (name) values ('Greece');
insert into plenum.country (name) values ('South Georgia and the South Sandwich Islands');
insert into plenum.country (name) values ('Guatemala');
insert into plenum.country (name) values ('Guam');
insert into plenum.country (name) values ('Guinea-Bissau');
insert into plenum.country (name) values ('Guyana');
insert into plenum.country (name) values ('Hong Kong');
insert into plenum.country (name) values ('Heard and McDonald Islands');
insert into plenum.country (name) values ('Honduras');
insert into plenum.country (name) values ('Croatia');
insert into plenum.country (name) values ('Haiti');
insert into plenum.country (name) values ('Hungary');
insert into plenum.country (name) values ('Indonesia');
insert into plenum.country (name) values ('Ireland');
insert into plenum.country (name) values ('Israel');
insert into plenum.country (name) values ('Isle of Man');
insert into plenum.country (name) values ('India');
insert into plenum.country (name) values ('British Indian Ocean Territory');
insert into plenum.country (name) values ('Iraq');
insert into plenum.country (name) values ('Iran');
insert into plenum.country (name) values ('Iceland');
insert into plenum.country (name) values ('Italy');
insert into plenum.country (name) values ('Jersey');
insert into plenum.country (name) values ('Jamaica');
insert into plenum.country (name) values ('Jordan');
insert into plenum.country (name) values ('Japan');
insert into plenum.country (name) values ('Kenya');
insert into plenum.country (name) values ('Kyrgyzstan');
insert into plenum.country (name) values ('Cambodia');
insert into plenum.country (name) values ('Kiribati');
insert into plenum.country (name) values ('Comoros');
insert into plenum.country (name) values ('Saint Kitts and Nevis');
insert into plenum.country (name) values ('North Korea');
insert into plenum.country (name) values ('South Korea');
insert into plenum.country (name) values ('Kuwait');
insert into plenum.country (name) values ('Cayman Islands');
insert into plenum.country (name) values ('Kazakhstan');
insert into plenum.country (name) values ('Lao People''s Democratic Republic');
insert into plenum.country (name) values ('Lebanon');
insert into plenum.country (name) values ('Saint Lucia');
insert into plenum.country (name) values ('Liechtenstein');
insert into plenum.country (name) values ('Sri Lanka');
insert into plenum.country (name) values ('Liberia');
insert into plenum.country (name) values ('Lesotho');
insert into plenum.country (name) values ('Lithuania');
insert into plenum.country (name) values ('Luxembourg');
insert into plenum.country (name) values ('Latvia');
insert into plenum.country (name) values ('Libya');
insert into plenum.country (name) values ('Morocco');
insert into plenum.country (name) values ('Monaco');
insert into plenum.country (name) values ('Moldova');
insert into plenum.country (name) values ('Montenegro');
insert into plenum.country (name) values ('Saint-Martin (France)');
insert into plenum.country (name) values ('Madagascar');
insert into plenum.country (name) values ('Marshall Islands');
insert into plenum.country (name) values ('Macedonia');
insert into plenum.country (name) values ('Mali');
insert into plenum.country (name) values ('Myanmar');
insert into plenum.country (name) values ('Mongolia');
insert into plenum.country (name) values ('Macau');
insert into plenum.country (name) values ('Northern Mariana Islands');
insert into plenum.country (name) values ('Martinique');
insert into plenum.country (name) values ('Mauritania');
insert into plenum.country (name) values ('Montserrat');
insert into plenum.country (name) values ('Malta');
insert into plenum.country (name) values ('Mauritius');
insert into plenum.country (name) values ('Maldives');
insert into plenum.country (name) values ('Malawi');
insert into plenum.country (name) values ('Mexico');
insert into plenum.country (name) values ('Malaysia');
insert into plenum.country (name) values ('Mozambique');
insert into plenum.country (name) values ('Namibia');
insert into plenum.country (name) values ('New Caledonia');
insert into plenum.country (name) values ('Niger');
insert into plenum.country (name) values ('Norfolk Island');
insert into plenum.country (name) values ('Nigeria');
insert into plenum.country (name) values ('Nicaragua');
insert into plenum.country (name) values ('The Netherlands');
insert into plenum.country (name) values ('Norway');
insert into plenum.country (name) values ('Nepal');
insert into plenum.country (name) values ('Nauru');
insert into plenum.country (name) values ('Niue');
insert into plenum.country (name) values ('New Zealand');
insert into plenum.country (name) values ('Oman');
insert into plenum.country (name) values ('Panama');
insert into plenum.country (name) values ('Peru');
insert into plenum.country (name) values ('French Polynesia');
insert into plenum.country (name) values ('Papua New Guinea');
insert into plenum.country (name) values ('Philippines');
insert into plenum.country (name) values ('Pakistan');
insert into plenum.country (name) values ('Poland');
insert into plenum.country (name) values ('St. Pierre and Miquelon');
insert into plenum.country (name) values ('Pitcairn');
insert into plenum.country (name) values ('Puerto Rico');
insert into plenum.country (name) values ('State of Palestine');
insert into plenum.country (name) values ('Portugal');
insert into plenum.country (name) values ('Palau');
insert into plenum.country (name) values ('Paraguay');
insert into plenum.country (name) values ('Qatar');
insert into plenum.country (name) values ('Réunion');
insert into plenum.country (name) values ('Romania');
insert into plenum.country (name) values ('Serbia');
insert into plenum.country (name) values ('Russian Federation');
insert into plenum.country (name) values ('Rwanda');
insert into plenum.country (name) values ('Saudi Arabia');
insert into plenum.country (name) values ('Solomon Islands');
insert into plenum.country (name) values ('Seychelles');
insert into plenum.country (name) values ('Sudan');
insert into plenum.country (name) values ('Sweden');
insert into plenum.country (name) values ('Singapore');
insert into plenum.country (name) values ('Saint Helena');
insert into plenum.country (name) values ('Slovenia');
insert into plenum.country (name) values ('Svalbard and Jan Mayen Islands');
insert into plenum.country (name) values ('Slovakia');
insert into plenum.country (name) values ('Sierra Leone');
insert into plenum.country (name) values ('San Marino');
insert into plenum.country (name) values ('Senegal');
insert into plenum.country (name) values ('Somalia');
insert into plenum.country (name) values ('Suriname');
insert into plenum.country (name) values ('South Sudan');
insert into plenum.country (name) values ('Sao Tome and Principe');
insert into plenum.country (name) values ('El Salvador');
insert into plenum.country (name) values ('Sint Maarten');
insert into plenum.country (name) values ('Syria');
insert into plenum.country (name) values ('Swaziland');
insert into plenum.country (name) values ('Turks and Caicos Islands');
insert into plenum.country (name) values ('Chad');
insert into plenum.country (name) values ('French Southern Territories');
insert into plenum.country (name) values ('Togo');
insert into plenum.country (name) values ('Thailand');
insert into plenum.country (name) values ('Tajikistan');
insert into plenum.country (name) values ('Tokelau');
insert into plenum.country (name) values ('Timor-Leste');
insert into plenum.country (name) values ('Turkmenistan');
insert into plenum.country (name) values ('Tunisia');
insert into plenum.country (name) values ('Tonga');
insert into plenum.country (name) values ('Turkey');
insert into plenum.country (name) values ('Trinidad and Tobago');
insert into plenum.country (name) values ('Tuvalu');
insert into plenum.country (name) values ('Taiwan');
insert into plenum.country (name) values ('Tanzania');
insert into plenum.country (name) values ('Ukraine');
insert into plenum.country (name) values ('Uganda');
insert into plenum.country (name) values ('United States Minor Outlying Islands');
insert into plenum.country (name) values ('United States');
insert into plenum.country (name) values ('Uruguay');
insert into plenum.country (name) values ('Uzbekistan');
insert into plenum.country (name) values ('Vatican');
insert into plenum.country (name) values ('Saint Vincent and the Grenadines');
insert into plenum.country (name) values ('Venezuela');
insert into plenum.country (name) values ('Virgin Islands (British)');
insert into plenum.country (name) values ('Virgin Islands (U.S.)');
insert into plenum.country (name) values ('Vietnam');
insert into plenum.country (name) values ('Vanuatu');
insert into plenum.country (name) values ('Wallis and Futuna Islands');
insert into plenum.country (name) values ('Samoa');
insert into plenum.country (name) values ('Yemen');
insert into plenum.country (name) values ('Mayotte');
insert into plenum.country (name) values ('South Africa');
insert into plenum.country (name) values ('Zambia');
insert into plenum.country (name) values ('Zimbabwe');

--Users
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('gsignorelli0', 'eMQ40cPHVgr', 'gsignorelli0@cloudflare.com', 'Gloriana Signorelli', 'Female', '9065 Miller Avenue', 'Kayveo', '8/8/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('aburdis1', 'eVruY8rB9us', 'aburdis1@linkedin.com', 'Ardine Burdis', 'Female', '12750 Heffernan Center', 'Brainsphere', '9/26/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('ckerfut2', 'xiZtGm1', 'ckerfut2@intel.com', 'Cairistiona Kerfut', 'Female', '09 Cody Trail', 'Topicstorm', '11/26/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('sduffet3', '6Jrygh', 'sduffet3@elegantthemes.com', 'Sheffy Duffet', 'Male', '71 Dottie Junction', 'Wikivu', '4/16/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('llanger4', '34G1lulS7Bz', 'llanger4@google.co.uk', 'Lindsay Langer', 'Female', '20 David Street', 'Agimba', '1/1/2018');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('mbauer5', 'E4rkY8tnvt7', 'mbauer5@dion.ne.jp', 'Meredithe Bauer', 'Female', '90 Ridgeview Crossing', 'Topdrive', '11/1/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('nwinkett6', 'tytfyuUdd', 'nwinkett6@dot.gov', 'Noel Winkett', 'Female', '9277 Schmedeman Junction', 'Zoombeat', '3/8/2018');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('anairn7', 'Tc2grOjvvRQB', 'anairn7@webnode.com', 'Agretha Nairn', 'Female', '0 2nd Place', 'Mybuzz', '5/16/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('mvala8', 'yi4KQi', 'mvala8@fotki.com', 'Maria Vala', 'Female', '0636 Atwood Circle', 'Zazio', '8/23/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('brappoport9', 'GGKIFksZmm', 'brappoport9@time.com', 'Bryana Rappoport', 'Female', '5311 Cody Court', 'Rhyloo', '12/1/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('bwardalea', 'mjrQImo', 'bwardalea@accuweather.com', 'Blythe Wardale', 'Female', '4927 Magdeline Lane', 'Centizu', '9/1/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('aeloyb', 'qcs2Rfl', 'aeloyb@google.com.br', 'Axel Eloy', 'Male', '72370 Orin Plaza', 'Realcube', '5/9/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('bsmoughtonc', 'axi3uln', 'bsmoughtonc@rakuten.co.jp', 'Beverley Smoughton', 'Female', '10480 Village Junction', 'Quimm', '6/11/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('lkibblewhited', 'MMNDkEZoYnp', 'lkibblewhited@hubpages.com', 'Liz Kibblewhite', 'Female', '81273 Southridge Plaza', 'Realfire', '6/10/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('kgrigolone', 'WZvFapm3ukr', 'kgrigolone@goo.ne.jp', 'Kayla Grigolon', 'Female', '033 Springs Circle', 'Photobug', '7/24/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('ymcf', 'UTBv8n', 'ymcf@etsy.com', 'Yulma Mc Ilwrick', 'Male', '86 Onsgard Street', 'Livetube', '12/7/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('kdaunayg', 'L2SQz3', 'kdaunayg@wp.com', 'Ketty Daunay', 'Female', '08 Talisman Terrace', 'Devcast', '10/14/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('dmunganh', 'Je4GrmjgHj', 'dmunganh@phoca.cz', 'Drucie Mungan', 'Female', '815 Del Sol Street', 'Aimbu', '8/7/2017');
insert into UserTable (userName, password, email, name, gender, address, institution, description, imgUrl) values ('dpiochi', '03INlP', 'dpiochi@businessweek.com', 'Dorian Pioch', 'Male', '600 Buell Court', 'Eidel', '6/7/2017');

--PremiumSignature
insert into plenum.premiumsignature (startDate, duration, idUser) values ('2017-02-25', '2017-10-19', 1);
insert into plenum.premiumsignature (startDate, duration, idUser) values ('2018-03-13', '2017-09-22', 2);
insert into plenum.premiumsignature (startDate, duration, idUser) values ('2017-02-07', '2018-03-12', 3);
insert into plenum.premiumsignature (startDate, duration, idUser) values ('2018-03-22', '2017-09-14', 4);
insert into plenum.premiumsignature (startDate, duration, idUser) values ('2017-10-11', '2017-04-09', 5);

--Project
insert into premium.project (creationDate, name, description, private) values ('2018-03-05', 'Tin', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', true);
insert into premium.project (creationDate, name, description, private) values ('2018-03-03', 'Treeflex', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true);
insert into premium.project (creationDate, name, description, private) values ('2018-03-18', 'Sub-Ex', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', false);
insert into premium.project (creationDate, name, description, private) values ('2018-03-14', 'Bamity', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', false);
insert into premium.project (creationDate, name, description, private) values ('2018-02-09', 'Voltsillam', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', true);

--Joined
